# Use an official Python runtime as a parent image
FROM python:3.6-slim

ARG RMQ_HOST
ENV RMQ_HOST=${RMQ_HOST}
ARG RMQ_PING_COMMANDER_RMQ_EXCHANGE
ENV RMQ_PING_COMMANDER_RMQ_EXCHANGE=${RMQ_PING_COMMANDER_RMQ_EXCHANGE}
ARG RMQ_PING_OPERATOR_RMQ_QUEUE_IN
ENV RMQ_PING_OPERATOR_RMQ_QUEUE_IN=${RMQ_PING_OPERATOR_RMQ_QUEUE_IN}
ARG DEVICE_CONFIG_BACKUP_DB_NAME
ENV DEVICE_CONFIG_BACKUP_DB_NAME=${DEVICE_CONFIG_BACKUP_DB_NAME}
ARG DEVICE_CONFIG_BACKUP_DB_USER_NAME
ENV DEVICE_CONFIG_BACKUP_DB_USER_NAME=${DEVICE_CONFIG_BACKUP_DB_USER_NAME}
ARG DEVICE_CONFIG_BACKUP_DB_PASSWORD
ENV DEVICE_CONFIG_BACKUP_DB_PASSWORD=${DEVICE_CONFIG_BACKUP_DB_PASSWORD}
ARG DEVICE_CONFIG_BACKUP_HOST_ADDRESS
ENV DEVICE_CONFIG_BACKUP_HOST_ADDRESS=${DEVICE_CONFIG_BACKUP_HOST_ADDRESS}

RUN apt-get update
RUN apt-get install -y git

# Set the working directory to /app
RUN mkdir -p /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Run app.py when the container launches
CMD ["python", "rmq_ping_commander.py"]